const cutter = [
  {
    title: "plantifive",
    text: "Animationsvideo als Werbung für eine Nachhaltigkeits- und Spendenkampagne der Jugendverbands SWD-EC.",
    button: "plati... was? >",
    buttonHref: "#",
    img1: "img/plantifive1.png",
    img2: "img/plantifive2.png",
    img3: "img/plantifive3.png",
    img4: "img/plantifive1.png",
    url: "https://www.philippjenny.de/plantifive",
  },
  {
    title: "earth in layers",
    text: "3D-Animation im Rahmen des Studiums, die den Aufbau der Erde erklären soll.",
    button: "Ich habe Explosion gehört? >",
    buttonHref: "#",
    img1: "img/world_animation.mp4",
    img2: false,
    img3: false,
    img4: "img/earth.png",
    url: "https://www.philippjenny.de/3d-animation",
  },
  {
    title: "paX anders",
    text: "Lyricvideo für ein spoken word Video als Einspieler bei einem Live-Event.",
    button: "Mehr sehen >",
    buttonHref: "#",
    img1: "img/paxan1.png",
    img2: "img/paxan2.png",
    img3: "img/paxan3.png",
    img4: "img/paxan1.png",
    url: "https://www.philippjenny.de/pax-anders",
  },
];

const webDev = [
  {
    title: "Starbucks Airlines",
    text: "„Mixed Brands“ <br /> Landingpage für die imaginäre Starbucks Airlines im Rahmen des Studiums.",
    button: "Kaffee? Fliegen? >",
    buttonHref: "#",
    img1: "img/sb1.jpg",
    img2: "img/sb2.jpg",
    img3: "img/sb3.jpg",
    img4: "img/sb1.jpg",
    url: "https://www.philippjenny.de/starbucks",
  },
  {
    title: "WLAN Dashboard",
    text: "3D-Animation im Rahmen des Studiums, die den Aufbau der Erde erklären soll.",
    button: "Das will ich ausprobieren! >",
    buttonHref: "#",
    img1: "img/wifi2.mp4",
    img2: false,
    img3: false,
    img4: "img/earth.png",
    url: "https://www.philippjenny.de/earth",
  },
  {
    title: "portfolio",
    text: "Lyricvideo für ein spoken word Video als Einspieler bei einem Live-Event.",
    button: "Zeig mir, wie du es gemacht hast! >",
    buttonHref: "#",
    img1: "img/pj1.png",
    img2: "img/pj2.png",
    img3: "img/pj3.png",
    img4: "img/pj1.png",
    url: "https://www.philippjenny.de/portfolio",
  },
];

const grafik = [
  {
    title: "Flyer JE-Freizeit",
    text: "Animationsvideo als Werbung für eine Nachhaltigkeits- und Spendenkampagne der Jugendverbands SWD-EC.",
    button: "Ja Grüezi! >",
    buttonHref: "#",
    img1: "img/jef1.png",
    img2: "img/jef2.png",
    img3: "img/jef3.png",
    img4: "img/jef1.png",
    url: "https://www.philippjenny.de/je-freizeit",
  },
  {
    title: "earth <br /> in layers",
    text: "3D-Animation im Rahmen des Studiums, die den Aufbau der Erde erklären soll.",
    button: "Ich habe Explosion gehört? >",
    buttonHref: "#",
    img1: "img/world_animation.mp4",
    img2: false,
    img3: false,
    img4: "img/earth.png",
    url: "https://www.philippjenny.de/earth",
  },
  {
    title: "paX anders",
    text: "Lyricvideo für ein spoken word Video als Einspieler bei einem Live-Event.",
    button: "Mehr sehen >",
    buttonHref: "#",
    img1: "img/paxan1.png",
    img2: "img/paxan2.png",
    img3: "img/paxan3.png",
    img4: "img/paxan1.png",
    url: "https://www.philippjenny.de/pax-anders",
  },
];
