const cutter = [
  {
    title: "planti&shy;five",
    text: "Animationsvideo als Werbung für eine Nachhaltigkeits- und Spendenkampagne der Jugendverbands SWD-EC.",
    button: "plati... was? >",
    buttonHref: "#",
    img1: "img/plantifive1.jpg",
    img2: "img/plantifive2.png",
    img3: "img/plantifive3.png",
    img4: "img/plantifive1.jpg",
    url: "https://www.philippjenny.de/plantifive",
    buttonLabel: "Plantifive >",
  },
  {
    title: "Logo Ani&shy;ma&shy;tio&shy;nen",
    text: "Animationsvideo als Werbung für eine Nachhaltigkeits- und Spendenkampagne der Jugendverbands SWD-EC.",
    button: "plati... was? >",
    buttonHref: "#",
    img1: "img/logo/logo_tmt.jpg",
    img2: "img/logo/logo_teennight.jpg",
    img3: "img/logo/logo_youpc.jpg",
    img4: "img/logo/logo_tmt.jpg",
    url: "https://www.philippjenny.de/plantifive",
    buttonLabel: "Logo Animationen >",
  },
  {
    title: "earth in layers",
    text: "3D-Animation im Rahmen des Studiums, die den Aufbau der Erde erklären soll.",
    button: "Ich habe Explosion gehört? >",
    buttonHref: "#",
    img1: "img/world_animation.mp4",
    img2: false,
    img3: false,
    img4: "img/earth.png",
    url: "https://www.philippjenny.de/3d-animation",
    buttonLabel: "earth in layers >",
  },
  {
    title: "Nebelleben",
    text: "Lyricvideo für ein spoken word Video als Einspieler bei einem Live-Event.",
    button: "Mehr sehen >",
    buttonHref: "#",
    img1: "img/paxan1.png",
    img2: "img/paxan2.png",
    img3: "img/paxan3.png",
    img4: "img/paxan1.png",
    url: "https://www.philippjenny.de/pax-anders",
    buttonLabel: "Nebelleben Poetry >",
  },
];

const webDev = [
  {
    title: "Weekleat App",
    text: "„Mixed Brands“ <br /> Landingpage für die imaginäre Starbucks Airlines im Rahmen des Studiums.",
    button: "Zur App >",
    buttonHref: "#",
    img1: "img/weekleat/images/weekleat_title.jpg",
    img2: "img/weekleat/images/weekleat_icon.jpg",
    img3: "img/weekleat/images/weekleat_cards.jpg",
    img4: "img/weekleat/images/weekleat_title.jpg",
    url: "https://www.philippjenny.de/weekleat",
    buttonLabel: "Weekleat App >",
  },
  {
    title: "Starbucks Airlines",
    text: "„Mixed Brands“ <br /> Landingpage für die imaginäre Starbucks Airlines im Rahmen des Studiums.",
    button: "Kaffee? Fliegen? >",
    buttonHref: "#",
    img1: "img/sb1.jpg",
    img2: "img/sb2.jpg",
    img3: "img/sb3.jpg",
    img4: "img/sb1.jpg",
    url: "https://www.philippjenny.de/starbucks",
    buttonLabel: "Starbucks Airlines >",
  },
  {
    title: "WLAN Dashboard",
    text: "3D-Animation im Rahmen des Studiums, die den Aufbau der Erde erklären soll.",
    button: "Das will ich ausprobieren! >",
    buttonHref: "#",
    img1: "img/wifi/wifi_video.mp4",
    img2: false,
    img3: false,
    img4: "img/wifi/wifi.jpg",
    url: "https://www.philippjenny.de/earth",
    buttonLabel: "WLAN Dashboard >",
  },
  {
    title: "portfolio",
    text: "Lyricvideo für ein spoken word Video als Einspieler bei einem Live-Event.",
    button: "Zeig mir, wie du es gemacht hast! >",
    buttonHref: "#",
    img1: "img/pj1.png",
    img2: "img/pj2.png",
    img3: "img/pj3.png",
    img4: "img/pj1.png",
    url: "https://www.philippjenny.de/portfolio",
    buttonLabel: "Portfolio >",
  },
];

const grafik = [
  {
    title: "Aben&shy;teuer&shy;zeit",
    text: "Animationsvideo als Werbung für eine Nachhaltigkeits- und Spendenkampagne der Jugendverbands SWD-EC.",
    button: "Ja Grüezi! >",
    buttonHref: "#",
    img1: "img/abenteuer/abenteuer_title.jpg",
    img2: "img/abenteuer/abenteuer_illu.jpg",
    img3: "img/abenteuer/abenteuer_photo.jpg",
    img4: "img/abenteuer/abenteuer_title_empty.jpg",
    url: "https://www.philippjenny.de/je-freizeit",
    buttonLabel: "Abenteuerzeit >",
  },
  {
    title: "Flyer JE-Freizeit",
    text: "Animationsvideo als Werbung für eine Nachhaltigkeits- und Spendenkampagne der Jugendverbands SWD-EC.",
    button: "Ja Grüezi! >",
    buttonHref: "#",
    img1: "img/jef1.png",
    img2: "img/jef2.png",
    img3: "img/jef3.png",
    img4: "img/jef1.png",
    url: "https://www.philippjenny.de/je-freizeit",
    buttonLabel: "Flyer-Sammlung >",
  },
  {
    title: "Four12",
    text: "3D-Animation im Rahmen des Studiums, die den Aufbau der Erde erklären soll.",
    button: "Ich habe Explosion gehört? >",
    buttonHref: "#",
    img1: "img/four12/four12_video.mp4",
    img2: false,
    img3: false,
    img4: "img/devnagari/devnagari_nike.jpg",
    url: "https://www.philippjenny.de/earth",
    buttonLabel: "Four12 >",
  },
  {
    title: "Devnagari Redesign",
    text: "Lyricvideo für ein spoken word Video als Einspieler bei einem Live-Event.",
    button: "Mehr sehen >",
    buttonHref: "#",
    img1: "img/devnagari/devnagari_subway.jpg",
    img2: "img/devnagari/devnagari_nike.jpg",
    img3: "img/devnagari/devnagari_subway_skizze.jpg",
    img4: "",
    url: "https://www.philippjenny.de/pax-anders",
    buttonLabel: "Devnagari Logo Redesign >",
  },
];
